[project]
name = "clearml-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clearml>=2.1.2",
    "tqdm>=4.67.1",
]
